### ISSUE TITLE
Support for Asian Languages

### ISSUE THREAD

**Issue by Wobbley** [bhaberer/cinch-links-titles#1]
Hey

I am having trouble with links-titles not displaying characters from Asian Languages, probably other characters as well. I did a quick search and it seems that nokogiri is to blame, not sure if this can be of any help: https://gist.github.com/827022/ee96dac12d4d0ce61f9597f091baa2771c6d6ab7

I am still pretty new to Ruby but I can give it a go and create a pull request if you want.

Your gem has been of great use so far :D

**Comment by bhaberer** [comment]
I don't seem to see this issue at all, what ruby and noikogiri are you using?

```
17:17 <@brian> http://www.nicovideo.jp/watch/1297306177
17:17 < marvin> http://www.nicovideo.jp/watch/1297306177 ∴ カードファイト!! ヴァンガード　第6話「謎のカードショップ」 ‐ ニコニコ動画:GINZA
```

**Comment by Wobbley** [comment]
Hey

Well good to know it's on my end +1

I am using docker with the 2-slim version (https://registry.hub.docker.com/_/ruby/), from the gemfile.lock I have the following version of Nokogiri:
    nokogiri (1.6.6.2)
      mini_portile (~> 0.6.0)
    nokogiri (1.6.6.2-x64-mingw32)
      mini_portile (~> 0.6.0)

I get this issue both when running locally on ubuntu and the docker instance even though the OS itself displays japanese characters just fine :/ If you have any pointers that would be great, but seems like this is a user error. So I will see if I can get it solved myself :)

EDIT: I just tried your link, and that works fine, if you try youtube links it fails though. Example:

14:27:02 <Wobbley> https://www.youtube.com/watch?v=cK3NMZAUKGw
14:27:02 <Derpy> https://www.youtube.com/watch?v=cK3NMZAUKGw ∴  BABYMETAL - ã¡ã®ãã - MEGITSUNE (Full ver.) - YouTube

**Comment by bhaberer** [comment]
Silly question, but are other users seeing the odd characters as well? Some
Clients don't handle utf8 that well.

On Wed, Apr 1, 2015 at 5:21 AM, Dean Lozo notifications@github.com wrote:

> Hey
> 
> Well good to know it's on my end +1
> 
> I am using docker with the 2-slim version (
> https://registry.hub.docker.com/_/ruby/), from the gemfile.lock I have
> the following version of Nokogiri:
> nokogiri (1.6.6.2)
> mini_portile (~> 0.6.0)
> nokogiri (1.6.6.2-x64-mingw32)
> mini_portile (~> 0.6.0)
> 
> I get this issue both when running locally on ubuntu and the docker
> instance even though the OS itself displays japanese characters just fine
> :/ If you have any pointers that would be great, but seems like this is a
> user error. So I will see if I can get it solved myself :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bhaberer/cinch-links-titles/issues/1#issuecomment-88456336
> .

## 
- Brian

**Comment by Wobbley** [comment]
No it's not just only me. I tired all the clients, and the log window for cinch itself, they all come out wrong. However the nicovideo links with japanese in them seem to work fine, youtube does not.

Could it be youtube specific? I can check Vimeo when I get home from work.
Does youtube work for you?
